general:
  collectTelemetryData: false

steps:
  cloudFoundryDeploy:
    cloudFoundry:
      credentialsId: 'd9e362a5-f7ef-4e57-be38-58da76043f90'
      apiEndpoint: 'https://api.cf.sap.hana.ondemand.com'
      org: 'epm'
      space: 'ye-test'
